# Generated by Django 6.1 on 2026-09-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_utilisateur_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='rh, finance, com...', max_length=32, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('ordre', models.PositiveSmallIntegerField(default=100, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Departement actif')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
                'db_table': 'departement',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='departements',
            field=models.ManyToManyField(blank=True, help_text="Les departements reels qui travaillent au quotidien dans cette application. Sert la vue globale de l'administration, pas le routage : distinct de « groupe ».", related_name='applications', to='comptes.departement', verbose_name='Departements servis'),
        ),
    ]
