# Generated by Django 6.1 on 2026-09-16 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_departement_application_departements'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Chef de departement'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.ForeignKey(blank=True, help_text="Le departement reel auquel cette personne est rattachee au quotidien — distinct des habilitations, qui donnent acces a une application mais ne disent pas d'ou vient la personne.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='comptes.departement', verbose_name='Departement'),
        ),
    ]
