# Generated by Django 6.1 on 2026-09-30 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_departement_responsable_utilisateur_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True, verbose_name='Adresse du service push')),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('agent', models.CharField(blank=True, max_length=300, verbose_name='Navigateur')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'abonnement_push',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(default='hub', max_length=32, verbose_name='Application')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Message')),
                ('lien', models.CharField(blank=True, max_length=300, verbose_name='Lien')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creee le')),
                ('lue_le', models.DateTimeField(blank=True, null=True, verbose_name='Lue le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-cree_le', '-id'],
                'indexes': [models.Index(fields=['utilisateur', 'lue_le'], name='notificatio_utilisa_2bc7c3_idx')],
            },
        ),
    ]
