# Generated by Django 6.1 on 2026-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False, help_text="Mot de passe provisoire : l'interface exige d'en choisir un nouveau avant tout autre ecran.", verbose_name='Mot de passe a changer'),
        ),
    ]
