# Generated by Django 6.0.8 on 2026-09-14 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('direction', 'Direction'), ('commercial', 'Commercial'), ('commercial_telephonique', 'Commercial téléphonique')], default='commercial', max_length=32)),
                ('actif', models.BooleanField(default=True)),
                ('adresse_contrat', models.TextField(blank=True, null=True)),
                ('piece_identite_ref', models.CharField(blank=True, max_length=191, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('nom_complet', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation', models.CharField(choices=[('agences', "Réseau d'agences"), ('commerciaux', 'Commerciaux directs')], default='agences', max_length=20)),
                ('fiche_adhesion', models.BooleanField(default=False)),
                ('contrat_modele', models.CharField(default='gda_bdm', max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'partenaires',
                'ordering': ['ordre', 'nom'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('chef', models.ForeignKey(blank=True, db_column='chef_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences_dirigees', to=settings.AUTH_USER_MODEL)),
                ('partenaire', models.ForeignKey(blank=True, db_column='partenaire_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences', to='core.partenaire')),
            ],
            options={
                'db_table': 'agences',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='agence',
            field=models.ForeignKey(blank=True, db_column='agence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.agence'),
        ),
        migrations.AddField(
            model_name='user',
            name='partenaire',
            field=models.ForeignKey(blank=True, db_column='partenaire_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.partenaire'),
        ),
        migrations.CreateModel(
            name='TypeCarte',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('partenaire', models.ForeignKey(blank=True, db_column='partenaire_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_cartes', to='core.partenaire')),
            ],
            options={
                'db_table': 'types_cartes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logged_in_at', models.DateTimeField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_logs',
                'ordering': ['-logged_in_at', '-id'],
                'managed': True,
            },
        ),
    ]
