# Generated by Django 6.0.8 on 2026-09-14 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('vente_carte', 'Vente de cartes'), ('enrolement_app', 'Enrôlement application')], default='vente_carte', max_length=30)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prime_meilleur_vendeur', models.DecimalField(decimal_places=0, default=25000, max_digits=12)),
                ('remise_pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remise_tous_types_cartes', models.BooleanField(default=True)),
                ('aide_hebdo_active', models.BooleanField(default=False)),
                ('aide_hebdo_montant', models.PositiveIntegerField(default=5000)),
                ('aide_hebdo_carburant', models.PositiveIntegerField(default=3000)),
                ('aide_hebdo_credit_tel', models.PositiveIntegerField(default=2000)),
                ('aide_hebdo_tous_commerciaux', models.BooleanField(default=True)),
                ('contrat_tous_commerciaux', models.BooleanField(default=True)),
                ('contrat_emolument_forfait', models.PositiveIntegerField(default=50000)),
                ('contrat_forfait_communication', models.PositiveIntegerField(default=2000)),
                ('contrat_forfait_deplacement', models.PositiveIntegerField(default=3000)),
                ('contrat_representant_nom', models.CharField(default='Yaya H DIALLO', max_length=191)),
                ('contrat_lieu_signature', models.CharField(default='Bamako', max_length=191)),
                ('contrat_clause_libre', models.TextField(blank=True, null=True)),
                ('contrat_publie_at', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('en_cours', 'En cours'), ('arretee', 'Arrêtée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='programmee', max_length=20)),
                ('toutes_agences', models.BooleanField(default=True)),
                ('partenaire', models.ForeignKey(blank=True, db_column='partenaire_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes', to='core.partenaire')),
            ],
            options={
                'db_table': 'campagnes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CampagneAction',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('donnees_apres', models.JSONField(blank=True, null=True)),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='campagnes.campagne')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campagne_actions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CampagneAgence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agence', models.ForeignKey(db_column='agence_id', on_delete=django.db.models.deletion.CASCADE, to='core.agence')),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, to='campagnes.campagne')),
            ],
            options={
                'db_table': 'campagne_agence',
                'managed': True,
                'unique_together': {('campagne', 'agence')},
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='agences',
            field=models.ManyToManyField(related_name='campagnes', through='campagnes.CampagneAgence', to='core.agence'),
        ),
        migrations.CreateModel(
            name='CampagneAideBeneficiaire',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, to='campagnes.campagne')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campagne_aide_beneficiaire',
                'managed': True,
                'unique_together': {('campagne', 'user')},
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='beneficiaires_aide',
            field=models.ManyToManyField(related_name='campagnes_aide', through='campagnes.CampagneAideBeneficiaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampagneAideVersement',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semaine_debut', models.DateField()),
                ('montant_carburant', models.PositiveIntegerField(default=0)),
                ('montant_credit_tel', models.PositiveIntegerField(default=0)),
                ('accuse_at', models.DateTimeField(blank=True, null=True)),
                ('accuse_commentaire', models.TextField(blank=True, null=True)),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, related_name='aide_versements', to='campagnes.campagne')),
                ('enregistre_par', models.ForeignKey(blank=True, db_column='enregistre_par', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='aide_versements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campagne_aide_versements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CampagneCommercialContrat',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, to='campagnes.campagne')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campagne_commercial_contrat',
                'managed': True,
                'unique_together': {('campagne', 'user')},
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='signataires_contrat',
            field=models.ManyToManyField(related_name='campagnes_signataire', through='campagnes.CampagneCommercialContrat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampagneContratArticle',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, related_name='contrat_articles', to='campagnes.campagne')),
            ],
            options={
                'db_table': 'campagne_contrat_articles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CampagneRemiseTypeCarte',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, to='campagnes.campagne')),
                ('type_carte', models.ForeignKey(db_column='type_carte_id', on_delete=django.db.models.deletion.CASCADE, to='core.typecarte')),
            ],
            options={
                'db_table': 'campagne_remise_type_carte',
                'managed': True,
                'unique_together': {('campagne', 'type_carte')},
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='types_cartes_remise',
            field=models.ManyToManyField(related_name='campagnes_remise', through='campagnes.CampagneRemiseTypeCarte', to='core.typecarte'),
        ),
        migrations.CreateModel(
            name='CommercialAgenceTransfert',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snapshots', models.JSONField()),
                ('note', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(db_column='admin_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferts_effectues', to=settings.AUTH_USER_MODEL)),
                ('commercial_user', models.ForeignKey(db_column='commercial_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferts_subis', to=settings.AUTH_USER_MODEL)),
                ('nouvelle_agence', models.ForeignKey(db_column='nouvelle_agence_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='core.agence')),
                ('profil_agence_apres', models.ForeignKey(blank=True, db_column='profil_agence_apres', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.agence')),
                ('profil_agence_avant', models.ForeignKey(blank=True, db_column='profil_agence_avant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.agence')),
            ],
            options={
                'db_table': 'commercial_agence_transferts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContratPrestationReponse',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='en_attente', max_length=32)),
                ('repondu_at', models.DateTimeField(blank=True, null=True)),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, related_name='contrat_reponses', to='campagnes.campagne')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contrat_reponses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contrat_prestation_reponses',
                'managed': True,
                'unique_together': {('campagne', 'user')},
            },
        ),
    ]
