# Generated by Django 6.0.8 on 2026-09-14 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagnes', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_carte', models.CharField(choices=[('vendue', 'Vendue'), ('activée', 'Activée'), ('en_erreur', 'En erreur')], default='vendue', max_length=20)),
                ('carte_identite', models.CharField(blank=True, max_length=255, null=True)),
                ('type_carte', models.ForeignKey(db_column='type_carte_id', on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='core.typecarte')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnrolementClient',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('numero_compte', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('agence', models.ForeignKey(blank=True, db_column='agence_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolements', to='core.agence')),
                ('campagne', models.ForeignKey(db_column='campagne_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrolements', to='campagnes.campagne')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrolements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrolement_clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=7)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('rang', models.IntegerField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='primes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'primes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('activation', 'Activation'), ('mot_de_passe', 'Mot de passe'), ('rechargement', 'Rechargement')], max_length=20)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='ouvert', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='terrain.client')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reclamations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut_activation', models.CharField(choices=[('vendue', 'Vendue'), ('activée', 'Activée'), ('en_erreur', 'En erreur')], default='vendue', max_length=20)),
                ('agence', models.ForeignKey(blank=True, db_column='agence_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='core.agence')),
                ('campagne', models.ForeignKey(blank=True, db_column='campagne_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='campagnes.campagne')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='terrain.client')),
                ('type_carte', models.ForeignKey(db_column='type_carte_id', on_delete=django.db.models.deletion.RESTRICT, related_name='ventes', to='core.typecarte')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdhesionCarte',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=191, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=191, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('pays_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_sur_carte', models.CharField(blank=True, max_length=100, null=True)),
                ('piece_type', models.CharField(blank=True, choices=[('cni', "Carte nationale d'identité"), ('passeport', 'Passeport'), ('nina', 'Carte NINA')], max_length=20, null=True)),
                ('piece_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('piece_delivree_le', models.DateField(blank=True, null=True)),
                ('piece_expire_le', models.DateField(blank=True, null=True)),
                ('piece_autorite', models.CharField(blank=True, max_length=191, null=True)),
                ('numero_compte_uba', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=191, null=True)),
                ('employeur', models.CharField(blank=True, max_length=191, null=True)),
                ('campagne', models.ForeignKey(blank=True, db_column='campagne_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adhesions', to='campagnes.campagne')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='terrain.client')),
                ('vente', models.OneToOneField(db_column='vente_id', on_delete=django.db.models.deletion.CASCADE, related_name='adhesion', to='terrain.vente')),
            ],
            options={
                'db_table': 'adhesions_cartes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TelephoniqueRapport',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_rapport', models.DateField()),
                ('appels_emis', models.PositiveIntegerField(default=0)),
                ('appels_joignables', models.PositiveIntegerField(default=0)),
                ('appels_non_joignables', models.PositiveIntegerField(default=0)),
                ('taux_joignabilite', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('clients_interesses_nombre', models.PositiveIntegerField(default=0)),
                ('clients_interesses_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('clients_deja_servis_nombre', models.PositiveIntegerField(default=0)),
                ('clients_deja_servis_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cartes_proposees', models.JSONField(blank=True, null=True)),
                ('propose_visa', models.PositiveIntegerField(default=0)),
                ('propose_gim', models.PositiveIntegerField(default=0)),
                ('propose_cauris', models.PositiveIntegerField(default=0)),
                ('propose_prepayee', models.PositiveIntegerField(default=0)),
                ('nj_repondeur', models.PositiveIntegerField(default=0)),
                ('nj_numero_errone', models.PositiveIntegerField(default=0)),
                ('nj_hors_reseau', models.PositiveIntegerField(default=0)),
                ('nj_autres_nombre', models.PositiveIntegerField(default=0)),
                ('nj_autres_precision', models.CharField(blank=True, max_length=255, null=True)),
                ('campagne', models.ForeignKey(blank=True, db_column='campagne_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephonique_rapports', to='campagnes.campagne')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='telephonique_rapports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telephonique_rapports',
                'managed': True,
                'unique_together': {('user', 'date_rapport')},
            },
        ),
    ]
