# Generated by Django 6.1 on 2026-10-02 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_remove_etapevalidation_avis_consultatif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuilvalidation',
            name='valideur_hierarchique',
            field=models.BooleanField(default=False, help_text="Si coche, l'etape revient au responsable du departement du demandeur, ou a defaut a son manager direct."),
        ),
        migrations.CreateModel(
            name='EvenementDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('SOUMISSION', 'Soumission'), ('MESSAGE', 'Message'), ('MISE_EN_ATTENTE', 'Mise en attente'), ('REPRISE', 'Reprise'), ('MODIFICATION', 'Modification'), ('APPROBATION', 'Approbation'), ('REJET', 'Rejet')], max_length=16)),
                ('texte', models.TextField(blank=True)),
                ('contexte', models.CharField(blank=True, max_length=160)),
                ('version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('instantane', models.JSONField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Evenement de dossier',
                'verbose_name_plural': 'Evenements de dossier',
                'ordering': ['cree_le', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_evenem_content_6efda6_idx')],
            },
        ),
    ]
