# Generated by Django 6.1 on 2026-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_journal_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementdossier',
            name='type',
            field=models.CharField(choices=[('SOUMISSION', 'Soumission'), ('MESSAGE', 'Message'), ('MISE_EN_ATTENTE', 'Mise en attente'), ('REPRISE', 'Reprise'), ('MODIFICATION', 'Modification'), ('APPROBATION', 'Approbation'), ('REJET', 'Rejet'), ('RELANCE', 'Relance')], max_length=16),
        ),
    ]
