# Generated by Django 6.1 on 2026-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='montant_estime',
            field=models.BooleanField(default=False, help_text='Coche si le montant est une estimation, pas un prix ferme.', verbose_name='Montant estimatif'),
        ),
    ]
